### ISSUE TITLE
NoSuchMethodError on creation of Mekanism Logic or Chemical channel 1.19.2

### ISSUE THREAD

**Issue by Codemonkey6658** [Terrails/XNetGasses#20]
[crash-2024-08-24_19.13.38-server.txt](https://github.com/user-attachments/files/16737461/crash-2024-08-24_19.13.38-server.txt)
with a message from mcjtylib   
[Netty Server IO #1/ERROR] [mcjtylib/]: Command 'xnet.controller.getChannelInfo' not handled!
[Netty Server IO #1/ERROR] [mcjtylib/]: Command 'xnet.controller.getConnectedBlocks' not handled!
when trying to create a Mekanism channel in a controller either connected to a network  or standalone
It will just not do anything after clicking the create button and 3-5 seconds later will just crash the game

**Comment by Terrails** [comment]
Seems like something weird happened with mappings in the file on CF/Modrinth as I couldn't reproduce it in dev nor when I built the mod again. It should be working with 4.1.6
